Import('RTT_ROOT')
Import('rtconfig')
from building import *

src = []

if  GetDepend('RT_USING_ADE7880'):
	src	= Glob('*.c')

cwd = GetCurrentDir()
CPPPATH = [
	cwd + '../../stm32f10x/Libraries/CMSIS/CM3/DeviceSupport/ST/STM32F10x',
]

#group = DefineGroup('finsh', src, depend = ['RT_USING_FINSH'], CPPPATH=CPPPATH, LINKFLAGS = LINKFLAGS, LIBRARY = '')
group = DefineGroup('ade7880', src,  depend = ['RT_USING_ADE7880'])

Return('group')
