#ifndef SPIFLASH_H__
#define SPIFLASH_H__

#include "sst25.h"


#define SPI_FLASH_SECTOR_SIZE	RT_DFS_ELM_MAX_SECTOR_SIZE
#define SPI_FLASH_SIZE 			SST25_VF016B_SIZE
#define SPI_FLASH_BLOCK_SIZE	SST25_VF016B_SECTOR_SIZE

#endif
