import os
import sys
import rtconfig
# import time

RTT_ROOT = os.path.normpath(os.getcwd() + '/../..')
sys.path = sys.path + [os.path.join(RTT_ROOT, 'tools')]

from building import *

# TARGET = 'rtthread-stm32.' + rtconfig.TARGET_EXT
# Standard ver:SCC_1.0.21.20120824_Beta_0
# TARGET = 'SCC_1.0.21.' + time.strftime('%Y%m%d',time.localtime()) + '_Beta_0' + rtconfig.TARGET_EXT
TARGET = rtconfig.TARGET_VER_NAME + rtconfig.TARGET_EXT

env = Environment(tools = ['mingw'],
	AS = rtconfig.AS, ASFLAGS = rtconfig.AFLAGS,
	CC = rtconfig.CC, CCFLAGS = rtconfig.CFLAGS,
	AR = rtconfig.AR, ARFLAGS = '-rc',
	LINK = rtconfig.LINK, LINKFLAGS = rtconfig.LFLAGS)

env.PrependENVPath('PATH', rtconfig.EXEC_PATH)

#default MD5
env.Decider('MD5-timestamp')

if rtconfig.PLATFORM == 'iar':
	env.Replace(CCCOM = ['$CC $CCFLAGS $CPPFLAGS $_CPPDEFFLAGS $_CPPINCFLAGS -o $TARGET $SOURCES'])
	env.Replace(ARFLAGS = [''])
	env.Replace(LINKCOM = ['$LINK $SOURCES $LINKFLAGS -o $TARGET --map project.map'])

Export('RTT_ROOT')
Export('rtconfig')

# compile __DATE__, __TIME__
# os.remove('./build/src/kservice.o')
# E:\SourceInsightWork\base-plateform-rt-thread\source\applications\database\sys_cfg_api.o
# E:\SourceInsightWork\base-plateform-rt-thread\source\bsp\stm32f103\build\components\finsh\cmd.o
# os.remove('./build/components/finsh/cmd.o')
if True == os.path.isfile('../../applications/database/sys_cfg_api.o'):
	os.remove('../../applications/database/sys_cfg_api.o')


# prepare building environment
objs = PrepareBuilding(env, RTT_ROOT)

# STM32 firemare library building script
objs = objs + SConscript('Libraries/SConscript', variant_dir='build/bsp/Libraries', duplicate=0)

# board drivers build script
objs = objs + SConscript('../drivers/SConscript', variant_dir='build/bsp/drivers', duplicate=0)
# include applications
objs = objs + SConscript('../../applications/SConscript', variant_dir='build/applications', duplicate=0)

#
#SetOption('implicit-cache', 1)

# build program 
env.Program(TARGET, objs, LIBS=['my'])

# end building 
EndBuilding(TARGET)
